DROP DATABASE SPRING;
DROP USER springuser@localhost;

CREATE DATABASE SPRING;
CREATE USER springuser@localhost IDENTIFIED BY 'springpassword';
ALTER USER 'springuser'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'springpassword';
GRANT ALL ON SPRING.* TO springuser@localhost;

USE SPRING;

CREATE TABLE IF NOT EXISTS USER_ACCOUNT(
	USER_ID VARCHAR(20),
	USER_NAME VARCHAR(20),
	PASSWORD VARCHAR(20),
	POSTCODE VARCHAR(8),
	ADDRESS VARCHAR(50),
	EMAIL VARCHAR(50),
	JOB VARCHAR(30),
	HOBBY VARCHAR(10),
    BIRTHDAY DATE,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS ITEM(
	ITEM_ID INTEGER(5) AUTO_INCREMENT,
	ITEM_NAME VARCHAR(20),
	PRICE INTEGER(6),
	DESCRIPTION VARCHAR(50),
	PICTURE_URL VARCHAR(20),
	PRIMARY KEY (ITEM_ID)
);

CREATE TABLE IF NOT EXISTS SALE(
	SALE_ID INTEGER(10),
	USER_ID VARCHAR(20),
	UPDATE_TIME TIMESTAMP,
	PRIMARY KEY (SALE_ID,USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT (USER_ID)
);

CREATE TABLE IF NOT EXISTS SALE_LINE(
	SALE_ID INTEGER(10),
	SALE_LINE_ID INTEGER(3),
	ITEM_ID INTEGER(5),
	QUANTITY INTEGER(1),
	UPDATE_TIME TIMESTAMP,
	PRIMARY KEY (SALE_ID,SALE_LINE_ID),
	FOREIGN KEY (SALE_ID) REFERENCES SALE (SALE_ID),
	FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
);

INSERT INTO ITEM VALUES (1,'レモン',50,'レモンに含まれるクエン酸は疲労回復に有効です。ビタミンＣも豊富です。','lemon.jpg');
INSERT INTO ITEM VALUES (2,'オレンジ',100,'ビタミンＣが豊富です。フレッシュジュースもオススメです。','orange.jpg');
INSERT INTO ITEM VALUES (3,'キウイ',200,'ビタミンＣが非常に豊富です。ダイエットや美容にオススメです。','kiui.jpg');
INSERT INTO ITEM VALUES (4,'ブドウ',300,'ポリフェノールを多く含み、抗酸化作用があります。','budou.jpg');
INSERT INTO ITEM VALUES (5,'イチゴ',800,'ビタミンＣやフラボノイドを多く含んでいます。','ichigo.jpg');
INSERT INTO ITEM VALUES (6,'みかん',1000,'シネフィリンを含み、風邪をひきにくくなると言われています。','mikan.jpg');

INSERT INTO USER_ACCOUNT VALUES ('USERID01','USERNAME01','PASSWD01','111-111','○○市××区','user01@kronos-jp.net','社会人','釣り','1979-01-01');
INSERT INTO USER_ACCOUNT VALUES ('USERID02','USERNAME02','PASSWD02','222-222','□□市■■区','user02@kronos-jp.net','社会人','野球','1979-06-30');
INSERT INTO USER_ACCOUNT VALUES ('USERID03','USERNAME03','PASSWD03','333-333','△△市▲▲区','user03@kronos-jp.net','学生','旅行','2000-12-31');

QUIT
